version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=magnet
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql
networks:
  mysql:
    driver: bridge

volumes:
  db:
    driver: local