version: '3.8'
services:
#  mysql:
#    image: mysql:8.0
#    restart: always
#    environment:
#      - MYSQL_DATABASE=magnet
#      - MYSQL_ROOT_PASSWORD=root
#    ports:
#      - '3306:3306'
#    volumes:
#      - db:/var/lib/mysql
#      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#    networks:
#      - mysql
  magnet:
    container_name: magnet
    image: ypydd88/magnet:latest
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
    ports:
      - "8081:80"

networks:
  mysql:
    driver: bridge
  spring:
    driver: bridge

volumes:
  db:
    driver: local