
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/magnet
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    jackson:
      time-zone: Europe/Dublin
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  codec:
    max-in-memory-size: 5MB

server:
  error:
    include-message: always # Return Customized Exception Message to Client
  port: 8080

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

openapi:
  service:
    title: Magnet doc
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


security:
  secret_key: ${SECURITY_SECRET_KEY}

aws:
  region: eu-west-1
  s3:
    mock: false
    buckets:
      resume: elasticbeanstalk-eu-west-1-845708981828

apilayer:
  key: ${RESUME_PARSER_API_KEY}
  resume:
    parser:
      url: https://api.apilayer.com/resume_parser/upload
  skills:
    url: https://api.apilayer.com/skills


langchain4j:
  chat-model:
    provider: openai
    openai:
      api-key: demo
      model-name: gpt-3.5-turbo
      temperature: 0.0
#      top-p: 1.0
#      max-tokens: 100
#      presence-penalty: 0.0
#      frequency-penalty: 0.0
      timeout: PT60S
#      max-retries: 3
#      log-requests: true
#      log-responses: true

logging:
  level:
    web: debug
    dev:
      langchain4j: debug
      ai4j:
        openai4j: DEBUG
